services:
  accounts:
    image: "trangbn/accounts:v1"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700mb
    networks:
      - ezmicroservice
  loans:
    image: "trangbn/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700mb
    networks:
      - ezmicroservice
  cards:
    image: "trangbn/cards:v1"
    container_name: cards-ms
    ports:
      - "9080:9080"
    deploy:
      resources:
        limits:
          memory: 700mb
    networks:
      - ezmicroservice
  networks:
    ezmicroservice:
      driver:"bridge"